"""adds-users

Revision ID: 789253084dd6
Revises: 4887bec4c4db
Create Date: 2025-06-12 16:04:00.907369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789253084dd6'
down_revision = '4887bec4c4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('book_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
